### ISSUE TITLE
Huawei Mate 20 Pro (LYA-L29) downgrade to 9.1

### ISSUE THREAD

**Issue by BigLebowski21** [ProfessorJTJ/HISuite-Proxy#151]
Hello ProfessorJTJ,

what do I want to achieve: I would like to install a different operating system (no Gapps) on my phone. for this I found a manual on the Internet with openKirin/ADB to flash AEX to my mobile phone. This only work with EMUI version 8/9 or 9.1.
So far so good.

That's how I came to your site and first of all I have to express a big thank you to you for making your knowledge freely available to us.

After I realized that it is not possible to downgrade directly from 11 to 9.1, I followed the following step by step instruction.

https://github.com/ProfessorJTJ/HISuite-Proxy/issues/127

It worked wonderfully, after several attempts.

I have managed the downgrade, unfortunately I only got to 11.0.0.139.

Now my phone is no longer recognized, also super/fast chaging are not possible. None of what I found  here worked. I can't downgrade or update anymore.

please help me Sir.

sorry, for my english. im from germany.

**Comment by ProfessorJTJ** [comment]
Hi, did you boot into erecovery and tried to update from there?

If so that didn't work, some users reported that using HarmonyTP USB fixes the issue with losing USB connection

https://gsmserver.com/harmony-tp-cable/

If that worked for you, you can use hisuite proxy to downgrade further, you can directly downgrade from 11 to 10.1 and then from 10.1 to 10.0 later from 10.0 to 9.1

**Comment by BigLebowski21** [comment]
wow, you are fast.

I'm actually trying over eRecovery.  but its still 11.0.0.139. 48% reached.

I do not have a harmony Cable.

i downgraded with HiProxy with your latest version. and HiSuite 10.1.0.550.
with 10.0.1.100 it doesn't worked, there i get always the information, after 50% installation "no internet...." or "please connect to..." something like that.

Ok, if i use 10.1, wich CUST and PRELOAD fils should i use.

[old CUST/PRELOAD 11.0.0.4]

first i tried directly to downgrade to 9.0 and 9.1 but i allways get the information that the installation couldn't work. and after inizializing at 4% the installation broke up.

**Comment by ProfessorJTJ** [comment]
Hisuite 10.0 cannot do upgrade or downgrades for emui 11 phones, but 10.1 can

Try downgrading from emui 11 to 10.1 using hisuite 10.1
If it failed inside the phone after verification, try picking firmwares from here

https://professorjtj.github.io/Downgrade/

**Comment by BigLebowski21** [comment]
ok, thank you first. short check, if it worked with eRecovery.

at first
HiSuite 10.1
BaseVersion from 11 to 10.1
CustVersion 11.0.0.4
PreloadVersion 11.0.0.4
.
.
.
up to version 9.1 CUST and PRELOAD always remain 11.0.0.4, or do I have to adjust them? is that correct?

**Comment by ProfessorJTJ** [comment]
> ok, thank you first. short check, if it worked with eRecovery.
> 
> at first HiSuite 10.1 BaseVersion from 11 to 10.1 CustVersion 11.0.0.4 PreloadVersion 11.0.0.4 . . . up to version 9.1 CUST and PRELOAD always remain 11.0.0.4, or do I have to adjust them? is that correct?

You have to use same x.y versions for base, cust and preload like
10.1 base
10.1 cust
10.1 preload

If you couldn't find 10.1 preload or cust you can use 10.0 instead of 10.1, but don't install cust or preload 11.0 on base 10.1

**Comment by BigLebowski21** [comment]
the eRecovery dosn't work to fix the USB issue.

i put back my SIM card, and now im updating to
DT.DEU 11.0.0.3.
But its just a custom version from my Provider.
i'll let the phone online overnight, perhaps my provider will force to update the latest version back again. (11.0.0.172)

So, there is no other solution without this harmony cable?
Or sd card?

**Comment by BigLebowski21** [comment]
hi Professor,

where can i download the emui for manual installation? (usb-C stick or nanoSD9

**Comment by demanxxx** [comment]
Good afternoon! Faced the same problem, downgraded the firmware from 11.0.0.160 to 11.0.0.138 (region c10). Erecovery doesn't help. Please help me find the firmware to update the OTG software to restore the usb

**Comment by ProfessorJTJ** [comment]
> Good afternoon! Faced the same problem, downgraded the firmware from 11.0.0.160 to 11.0.0.138 (region c10). Erecovery doesn't help. Please help me find the firmware to update the OTG software to restore the usb

Hi, send your hisuite log please.
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

**Comment by demanxxx** [comment]
[https://disk.yandex.ru/d/WtQ138n3cSmfXA](url)

**Comment by ProfessorJTJ** [comment]
> in archive https://disk.yandex.ru/d/WtQ138n3cSmfXA

This log is from a phone on 11.0.0.138
And as the log is generated the USB is working and connected to a pc.

Are you sure you downgraded from 11.0.0.160?

Please explain step by step and slowly, everything you did and the issue you're facing.

**Comment by demanxxx** [comment]
Yes, I downgrade from 11.0.0.160
Hisuite version 11.0.0.500 CN is synchronized via WLAN, as usb does not work.
Now I want to bring everything back
What I did:
using hisuite 11.0.0.510 +hisuite proxy flashed LYA-LGRP2-OVS 11.0.0.138, I wanted to downgrade to 10.1, then to 9. But faced with the problem of not working usb connection failed.

**Comment by o2809013** [comment]
Hi, i have same device in same condition. LYA-L09 C432  11.0.0.200. I try to downgrade few times but no succes.  I have harmony tp cable, hcu client, DC phoenix, sigmakey box, chimera tool, octoplus box and EFT dongle. Is there any solution with this equipments, i can try for you.

**Comment by ProfessorJTJ** [comment]
> Hi, i have same device in same condition. LYA-L09 C432 11.0.0.200. I try to downgrade few times but no succes. I have harmony tp cable, hcu client, DC phoenix, sigmakey box, chimera tool, octoplus box and EFT dongle. Is there any solution with this equipments? I can try for you.

Hi, unfortunately Huawei blocks downgrades, but have you tried the firmwares which are in "Downgrade" section?

https://professorjtj.github.io/Downgrade

Some people also reported that downgrading to emui 10.0 instead of 10.1 succeeds...

**Comment by demanxxx** [comment]
Soldered harmony TP cable. Please tell me if the hisuite phone will be visible in the test point mode? or this cable needs to be used with other software

**Comment by ProfessorJTJ** [comment]
> Soldered harmony TP cable. Please tell me if the hisuite phone will be visible in the test point mode? or this cable needs to be used with other software

As far as I'm concerned, it doesn't need special software. It's supposed to work.

**Comment by o2809013** [comment]
Not detect hisuite with harmony tp cable in tp mode. I have official factory software (board software). Hcu client and EFT dongle detect phone with tp cable but no response. I think there is no solution for now. Because new security patch blocks everything.

**Comment by o2809013** [comment]
This cable works grate

https://chimeratool.com/tr/docs/huawei-harmonyos-support

But you need first connect to phone side otherwise PC detect unknown USB device.

**Comment by BigLebowski21** [comment]
> Hisuite 10.0 cannot do upgrade or downgrades for emui 11 phones, but 10.1 can
> 
> Try downgrading from emui 11 to 10.1 using hisuite 10.1 If it failed inside the phone after verification, try picking firmwares from here
> 
> https://professorjtj.github.io/Downgrade/

Hi ProfessorJtJ,

sry for my late response. I have the cable now.
I can see it in my Explorer but can't enter the phone to see my folders.
HiSuite can't find an show my mobile.

I tried with this combination:

LYA-LGRP2-OVS 10.1.0.271
LYA-L29-CUST 10.0.0.7(C432)
LYA-L29-PRELOAD 10.0.0.5(C432R1)

and this

LYA-LGRP2-OVS 10.1.0.328
LYA-L29-CUST 10.0.0.8(C432)
LYA-L29-PRELOAD 10.0.0.5(C432R1)


 [15:39:10]: Checking if HISuite is Installed...
 [15:39:11]: HiSuite Exists, Proceeding...
 [15:39:11]: Closing HISuite....
 [15:39:13]: Checking HISuite Version...
 [15:39:14]: HiSuite Version 10 Is Installed, Proceeding....
 [15:39:14]: Patching HISuite Files....
 [15:39:15]: Patch succeeded, Proceeding....
 [15:39:15]: Checking HISuite Proxy Settings...
 [15:39:16]: Successfully Set Proxy Settings, Proceeding...
 [15:39:16]: Checking Hosts File For Redundant Entries....
 [15:39:17]: Hosts File Is Already Neat, Proceeding...
 [15:39:17]: Checking Connection To HISuite Proxy....
 [15:39:18]: HISuite Proxy Is On And Working.
 [15:39:18]: 
 [15:39:19]: Checks Finished, You can proceed to installation now!

HiSuite just told me to start the fastboot mode.
I did this but after a while it broke up with the message, device not supported please go to a service center. 

HuSuite v 10.1.0.550_OVE or should i try something different? 

Or should i jump directly to 10.0? But HiSuite doesn't find de device.

I need help, please.

[This is the cable i bought.](https://de.aliexpress.com/item/1005003414526364.html?spm=a2g0o.productlist.0.0.5b675f16VEjlDB&algo_pvid=5b5633fb-7671-4cc3-992a-563957632b73&algo_exp_id=5b5633fb-7671-4cc3-992a-563957632b73-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000025682316544%22%7D&pdp_pi=-1%3B7.05%3B-1%3B-1%40salePrice%3BEUR%3Bsearch-mainSearch)

**Comment by ProfessorJTJ** [comment]
> > Hisuite 10.0 cannot do upgrade or downgrades for emui 11 phones, but 10.1 can
> > Try downgrading from emui 11 to 10.1 using hisuite 10.1 If it failed inside the phone after verification, try picking firmwares from here
> > https://professorjtj.github.io/Downgrade/
> 
> Hi ProfessorJtJ,
> 
> sry for my late response. I have the cable now. I can see it in my Explorer but can't enter the phone to see my folders. HiSuite can't find an show my mobile.
> 
> I tried with this combination:
> 
> LYA-LGRP2-OVS 10.1.0.271 LYA-L29-CUST 10.0.0.7(C432) LYA-L29-PRELOAD 10.0.0.5(C432R1)
> 
> and this
> 
> LYA-LGRP2-OVS 10.1.0.328 LYA-L29-CUST 10.0.0.8(C432) LYA-L29-PRELOAD 10.0.0.5(C432R1)
> 
> [15:39:10]: Checking if HISuite is Installed... [15:39:11]: HiSuite Exists, Proceeding... [15:39:11]: Closing HISuite.... [15:39:13]: Checking HISuite Version... [15:39:14]: HiSuite Version 10 Is Installed, Proceeding.... [15:39:14]: Patching HISuite Files.... [15:39:15]: Patch succeeded, Proceeding.... [15:39:15]: Checking HISuite Proxy Settings... [15:39:16]: Successfully Set Proxy Settings, Proceeding... [15:39:16]: Checking Hosts File For Redundant Entries.... [15:39:17]: Hosts File Is Already Neat, Proceeding... [15:39:17]: Checking Connection To HISuite Proxy.... [15:39:18]: HISuite Proxy Is On And Working. [15:39:18]: [15:39:19]: Checks Finished, You can proceed to installation now!
> 
> HiSuite just told me to start the fastboot mode. I did this but after a while it broke up with the message, device not supported please go to a service center.
> 
> HuSuite v 10.1.0.550_OVE or should i try something different?
> 
> Or should i jump directly to 10.0? But HiSuite doesn't find de device.
> 
> I need help, please.
> 
> [This is the cable i bought.](https://de.aliexpress.com/item/1005003414526364.html?spm=a2g0o.productlist.0.0.5b675f16VEjlDB&algo_pvid=5b5633fb-7671-4cc3-992a-563957632b73&algo_exp_id=5b5633fb-7671-4cc3-992a-563957632b73-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000025682316544%22%7D&pdp_pi=-1%3B7.05%3B-1%3B-1%40salePrice%3BEUR%3Bsearch-mainSearch)

Connect the cable to your phone first then connect your cable to the pc, see if hisuite is able to recognise and connect to your phone.

**Comment by BigLebowski21** [comment]
> > > Hisuite 10.0 cannot do upgrade or downgrades for emui 11 phones, but 10.1 can
> > > Try downgrading from emui 11 to 10.1 using hisuite 10.1 If it failed inside the phone after verification, try picking firmwares from here
> > > https://professorjtj.github.io/Downgrade/
> > 
> > 
> > Hi ProfessorJtJ,
> > sry for my late response. I have the cable now. I can see it in my Explorer but can't enter the phone to see my folders. HiSuite can't find an show my mobile.
> > I tried with this combination:
> > LYA-LGRP2-OVS 10.1.0.271 LYA-L29-CUST 10.0.0.7(C432) LYA-L29-PRELOAD 10.0.0.5(C432R1)
> > and this
> > LYA-LGRP2-OVS 10.1.0.328 LYA-L29-CUST 10.0.0.8(C432) LYA-L29-PRELOAD 10.0.0.5(C432R1)
> > [15:39:10]: Checking if HISuite is Installed... [15:39:11]: HiSuite Exists, Proceeding... [15:39:11]: Closing HISuite.... [15:39:13]: Checking HISuite Version... [15:39:14]: HiSuite Version 10 Is Installed, Proceeding.... [15:39:14]: Patching HISuite Files.... [15:39:15]: Patch succeeded, Proceeding.... [15:39:15]: Checking HISuite Proxy Settings... [15:39:16]: Successfully Set Proxy Settings, Proceeding... [15:39:16]: Checking Hosts File For Redundant Entries.... [15:39:17]: Hosts File Is Already Neat, Proceeding... [15:39:17]: Checking Connection To HISuite Proxy.... [15:39:18]: HISuite Proxy Is On And Working. [15:39:18]: [15:39:19]: Checks Finished, You can proceed to installation now!
> > HiSuite just told me to start the fastboot mode. I did this but after a while it broke up with the message, device not supported please go to a service center.
> > HuSuite v 10.1.0.550_OVE or should i try something different?
> > Or should i jump directly to 10.0? But HiSuite doesn't find de device.
> > I need help, please.
> > [This is the cable i bought.](https://de.aliexpress.com/item/1005003414526364.html?spm=a2g0o.productlist.0.0.5b675f16VEjlDB&algo_pvid=5b5633fb-7671-4cc3-992a-563957632b73&algo_exp_id=5b5633fb-7671-4cc3-992a-563957632b73-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000025682316544%22%7D&pdp_pi=-1%3B7.05%3B-1%3B-1%40salePrice%3BEUR%3Bsearch-mainSearch)
> 
> Connect the cable to your phone first then connect your cable to the pc, see if hisuite is able to recognise and connect to your phone.

wait... meanwhile HiSuite are able to install. I'm downgrading now to 11.0.0.138 at first.

At first HDB doesn't work. after a while and some disconnect an connect (USB to PC) HDB was installing. 
Or, because I chanced the version. i don't know. i also enable "OEM-Block" and "ADB during charging" befor the HDB connection worked. I'm also able to navigate truth my mobile with the explorer.

i'll report. it took a while. actually installing. 5%

**Comment by BigLebowski21** [comment]
> > > > Hisuite 10.0 cannot do upgrade or downgrades for emui 11 phones, but 10.1 can
> > > > Try downgrading from emui 11 to 10.1 using hisuite 10.1 If it failed inside the phone after verification, try picking firmwares from here
> > > > https://professorjtj.github.io/Downgrade/
> > > 
> > > 
> > > Hi ProfessorJtJ,
> > > sry for my late response. I have the cable now. I can see it in my Explorer but can't enter the phone to see my folders. HiSuite can't find an show my mobile.
> > > I tried with this combination:
> > > LYA-LGRP2-OVS 10.1.0.271 LYA-L29-CUST 10.0.0.7(C432) LYA-L29-PRELOAD 10.0.0.5(C432R1)
> > > and this
> > > LYA-LGRP2-OVS 10.1.0.328 LYA-L29-CUST 10.0.0.8(C432) LYA-L29-PRELOAD 10.0.0.5(C432R1)
> > > [15:39:10]: Checking if HISuite is Installed... [15:39:11]: HiSuite Exists, Proceeding... [15:39:11]: Closing HISuite.... [15:39:13]: Checking HISuite Version... [15:39:14]: HiSuite Version 10 Is Installed, Proceeding.... [15:39:14]: Patching HISuite Files.... [15:39:15]: Patch succeeded, Proceeding.... [15:39:15]: Checking HISuite Proxy Settings... [15:39:16]: Successfully Set Proxy Settings, Proceeding... [15:39:16]: Checking Hosts File For Redundant Entries.... [15:39:17]: Hosts File Is Already Neat, Proceeding... [15:39:17]: Checking Connection To HISuite Proxy.... [15:39:18]: HISuite Proxy Is On And Working. [15:39:18]: [15:39:19]: Checks Finished, You can proceed to installation now!
> > > HiSuite just told me to start the fastboot mode. I did this but after a while it broke up with the message, device not supported please go to a service center.
> > > HuSuite v 10.1.0.550_OVE or should i try something different?
> > > Or should i jump directly to 10.0? But HiSuite doesn't find de device.
> > > I need help, please.
> > > [This is the cable i bought.](https://de.aliexpress.com/item/1005003414526364.html?spm=a2g0o.productlist.0.0.5b675f16VEjlDB&algo_pvid=5b5633fb-7671-4cc3-992a-563957632b73&algo_exp_id=5b5633fb-7671-4cc3-992a-563957632b73-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000025682316544%22%7D&pdp_pi=-1%3B7.05%3B-1%3B-1%40salePrice%3BEUR%3Bsearch-mainSearch)
> > 
> > 
> > Connect the cable to your phone first then connect your cable to the pc, see if hisuite is able to recognise and connect to your phone.
> 
> wait... meanwhile HiSuite are able to install. I'm downgrading now to 11.0.0.138 at first.
> 
> At first HDB doesn't work. after a while and some disconnect an connect (USB to PC) HDB was installing. Or, because I chanced the version. i don't know. i also enable "OEM-Block" and "ADB during charging" befor the HDB connection worked. I'm also able to navigate truth my mobile with the explorer.
> 
> i'll report. it took a while. actually installing. 5%

The first downgrade worked. (to 11.0.0.138)

After i tried to step down to 10.1 (B10.1.0.271/C10.0.0.7/P10.0.0.5).
I get the massage "Datapartition corrupted. Format the Partition to continue" on the phone.
I can chose "low-level-Format" or "Power off".

**Comment by ProfessorJTJ** [comment]
Because you didn't choose OS type as Rollback.

Wipe your data and it should be fixed.

**Comment by BigLebowski21** [comment]
> Wipe your data and it should be fixed.

ok, it works.
But still can't connect with original cabel.
for unlocking my Fast-Boot Mode to flash with OpenKirin AEX i have to step down to 9.0.
I'll report.

**Comment by demanxxx** [comment]
Good afternoon! Tell me please. Is it possible to use hisuiteproxy on the Hisuite version for China? To update over the WLAN?

**Comment by BigLebowski21** [comment]
> Because you didn't choose OS type as Rollback.
> 
> Wipe your data and it should be fixed.

So, at the end i finished with a new problem.

After i reached 10.0.0.154 i decide to update again to see which steps are used. and go the way back.

B: 10.0.0.154 -> C: 10.0.0.7 -> P: 10.0.0.5
B: 10.1.0.270 -> C: 10.0.0.7 -> P: 10.0.0.5
B: 10.1.0.288 -> C: 10.0.0.7 -> P: 10.0.0.5
B: 10.1.0.318 -> C: 10.0.0.8 -> P: 10.0.0.5
B: 10.1.0.328 -> C: 10.0.0.8 -> P: 10.0.0.5
B: 11.0.0.138 -> C: 11.0.0.4 -> P: 11.0.0.4
B: 11.0.0.200 -> C: 11.0.0.4 -> P: 11.0.0.4 

From 11.0.0.200 I'm not able to downgrade to 11.0.0.139.
HiSuite says the installation was successfully, on the phone Software install failed at 4%.

With 11.0.0.200 the supercharge are working again. Also the original USB-C cable,

**Comment by BigLebowski21** [comment]
https://github.com/ProfessorJTJ/HISuite-Proxy/issues/151#issuecomment-1024431029

Hi ProfessorJTJ,

here my systemupdate log and adb log.
[SystemUpdate_20220129_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7963716/SystemUpdate_20220129_00.log)
[Adb.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7963717/Adb.log)

**Comment by BigLebowski21** [comment]
> Because you didn't choose OS type as Rollback.
> 
> Wipe your data and it should be fixed.

Hi ProfessorJTJ,

here my systemupdate log and adb log
[SystemUpdate_20220129_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7963726/SystemUpdate_20220129_00.log)
[Adb.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7963728/Adb.log)
.

**Comment by ProfessorJTJ** [comment]
> > Because you didn't choose OS type as Rollback.
> > Wipe your data and it should be fixed.
> 
> [#151 (comment)](https://github.com/ProfessorJTJ/HISuite-Proxy/issues/151#issuecomment-1024431029)
> 
> Hi ProfessorJTJ,
> 
> here my systemupdate log and adb log [SystemUpdate_20220129_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7963726/SystemUpdate_20220129_00.log) [Adb.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7963728/Adb.log) .
> 
> I don't know how to interpret the logs. Can you help me, please?

Do you have the other log file from the say you successfully downgraded from emui 11?

**Comment by BigLebowski21** [comment]
> > > Because you didn't choose OS type as Rollback.
> > > Wipe your data and it should be fixed.
> > 
> > 
> > [#151 (comment)](https://github.com/ProfessorJTJ/HISuite-Proxy/issues/151#issuecomment-1024431029)
> > Hi ProfessorJTJ,
> > here my systemupdate log and adb log [SystemUpdate_20220129_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7963726/SystemUpdate_20220129_00.log) [Adb.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7963728/Adb.log) .
> > I don't know how to interpret the logs. Can you help me, please?
> 
> Do you have the other log file from the day you successfully downgraded from emui 11?

I deleted it.

Give me a moment. Perhaps i can recover it.

Meanwhile, I'll try it again, but i set the sim in and updated the provider Software. (That was the last different)

Perhaps was this the bug.

**Comment by BigLebowski21** [comment]
> 
[Adb.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7963844/Adb.log)
[SystemUpdate_20220125_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/7963845/SystemUpdate_20220125_00.log)

**Comment by ProfessorJTJ** [comment]
Well good luck but Huawei started blocking downgrades in newer versions, and with each new update they fix more bugs and block more downgrades.

You could try different rom versions hoping for one to downgrade or using dload firmwares of older 11 emuis, sometimes they work.

You could also try roms from the site's downgrade section
https://professorjtj.github.io/Downgrade

**Comment by BigLebowski21** [comment]
> Well good luck but Huawei started blocking downgrades in newer versions, and with each new update they fix more bugs and block more downgrades.
> 
> You could try different rom versions hoping for one to downgrade or using dload firmwares of older 11 emuis, sometimes they work.
> 
> You could also try roms from the site's downgrade section https://professorjtj.github.io/Downgrade

Thanks.

I already tried with the downgrade roms.

Can you see something useful in the logs?

**Comment by TehranMarket** [comment]
> Good afternoon! I found the build version 160 for the c10 region, I specified offlinepkg in hisuiteproxy. I connected hisuite CN+hisuiteproxy via wlan to the phone, I press update, and he writes that the latest version is 138 [https://d.radikal.ru/d33/2202/cb/e0be13d00735.jpg](url)

You need to know the rom id to be able to install it, and you need Huawei's old firmware link, like:

http://update.dbankcdn.com/TDS/data/files/p3/s15/G3886/g1650/v524088/f1/full/

v52408 is where the roms ids should be placed.

**Comment by ProfessorJTJ** [comment]
> is there any way to find out the rom ID?

Where did you get the rom from?
Is it a dload?

**Comment by demanxxx** [comment]
this rom was taken from downloaded in hisuite when rolling back from emui 12 beta
this is not dload

**Comment by ProfessorJTJ** [comment]
> this rom was taken from downloaded in hisuite when rolling back from emui 12 beta this is not dload

You will find the ids in hisuite log
C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log

You should open the log of the day you downgraded

**Comment by demanxxx** [comment]
> > this rom was taken from downloaded in hisuite when rolling back from emui 12 beta this is not dload
> 
> You will find the ids in hisuite log C:/Users/Your user/App Data/Local/HiSuite/log/Systemupdate.log
> 
> You should open the log of the day you downgraded

Unfortunately, the logs from that time were deleted, because I tried different versions of hisuite

**Comment by demanxxx** [comment]
found a link to the firmware
Can you help me find the ROM ID ?
http://update.dbankcdn.com/download/data/pub_13/HWHOTA_hota_900_9/42/v3/-ucLtIYNS52k7JBZdsD89w/full/update_full_base.zip

**Comment by demanxxx** [comment]
tell me at least approximately how to find this rom id.
With the rom id from build 138, the firmware is filled in, but at the firmware stage an error already appears in the phone

**Comment by ProfessorJTJ** [comment]
> tell me at least approximately how to find this rom id. With the rom id from build 138, the firmware is filled in, but at the firmware stage an error already appears in the phone

The id might have been temporarily, and now is no longer usable. ( disapproved by Huawei )

I couldn't find the rom's id, but if I have your device certificates, I might be able to get that id ( not guaranteed, but might work )

To do that you'd need to tick "Debug Logging" in hisuite proxy, click on update in hisuite and send the file 'logs.txt' which is in hisuite folder, to me.

**Comment by demanxxx** [comment]
[logs.zip](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8067548/logs.zip)

**Comment by demanxxx** [comment]
In general, I fixed the phone
I rolled back over the wlan to emui 9.1, then started offering builds on OTA, and in the end it already offered build 160 itself
