### ISSUE TITLE
Viruses

### ISSUE THREAD

**Issue by gchmurka123** [ProfessorJTJ/HISuite-Proxy#205]
in rar archive files antivirus reports malware:

https://www.virustotal.com/gui/file/c0566314f33946b6272fe5d32a530d02cdf8a11da9be9fcf92e10b8660da8db9

Even if I will run in the sandbox for the test, I still have to connect the phone. The HiSuite application has all permissions for my phone, so with HiSuite-proxy malware I am worried about data leakage from my device (contacts, saved files/photos and messages, data from apps, etc).

**Comment by ProfessorJTJ** [comment]
I'm aware of that but unfortunately I cannot fix it, though it's not related to the codes

You can replicate that error, just get a programming application like visual studio, create an empty c++ application

Scan it for viruses, it will show it as trojan

https://developercommunity.visualstudio.com/t/windows-defender-reports-a-trojan-1/1046937

**Comment by Bobbimus** [comment]
Shouldnt this be fixed now as mentioned here https://developercommunity.visualstudio.com/t/windows-defender-reports-a-trojan-1/1046937?

**Comment by ProfessorJTJ** [comment]
> Shouldnt this be fixed now as mentioned here https://developercommunity.visualstudio.com/t/windows-defender-reports-a-trojan-1/1046937?

The application is built and compiled using Visual Studio 2022, the "fix" on that topic belongs to 2020, my files must be already up to date, but as you see the issue still persists
